//! D-Bus proxy for `org.kde.StatusNotifierItem` and property loading.

use std::str::FromStr;

use zbus::{Connection, proxy};
use zbus::zvariant::OwnedObjectPath;

use crate::{
    error::Result,
    icon::{decode_pixmap, resolve_icon},
    types::{ItemStatus, StatusNotifierItem, TrayIconPixmap},
};

/// Raw pixmap tuple as transmitted by SNI: `(width, height, argb_data)`.
type RawPixmap = (i32, i32, Vec<u8>);

/// zbus proxy for the `org.kde.StatusNotifierItem` interface.
///
/// Apps may register at any object path; we default to `/StatusNotifierItem`
/// and also probe AppIndicator paths when needed.
#[proxy(
    interface = "org.kde.StatusNotifierItem",
    default_path = "/StatusNotifierItem"
)]
trait StatusNotifierItemInterface {
    /// Application identifier.
    #[zbus(property)]
    fn id(&self) -> zbus::Result<String>;

    /// Human-readable title.
    #[zbus(property)]
    fn title(&self) -> zbus::Result<String>;

    /// Current status: `Passive`, `Active`, or `NeedsAttention`.
    #[zbus(property)]
    fn status(&self) -> zbus::Result<String>;

    /// Freedesktop icon theme name for the primary icon.
    #[zbus(property)]
    fn icon_name(&self) -> zbus::Result<String>;

    /// Raw pixmap data for the primary icon.
    #[zbus(property)]
    fn icon_pixmap(&self) -> zbus::Result<Vec<RawPixmap>>;

    /// Icon name for the overlay icon.
    #[zbus(property)]
    fn overlay_icon_name(&self) -> zbus::Result<String>;

    /// Raw pixmap data for the overlay icon.
    #[zbus(property)]
    fn overlay_icon_pixmap(&self) -> zbus::Result<Vec<RawPixmap>>;

    /// Icon name used when `status == NeedsAttention`.
    #[zbus(property)]
    fn attention_icon_name(&self) -> zbus::Result<String>;

    /// Raw pixmap data for the attention icon.
    #[zbus(property)]
    fn attention_icon_pixmap(&self) -> zbus::Result<Vec<RawPixmap>>;

    /// Object path of the `com.canonical.dbusmenu` context menu.
    #[zbus(property)]
    fn menu(&self) -> zbus::Result<OwnedObjectPath>;

    /// Tooltip as a struct: `(icon_name, icon_pixmap, title, description)`.
    #[zbus(property)]
    fn tool_tip(&self) -> zbus::Result<(String, Vec<RawPixmap>, String, String)>;

    /// Signals — received via `receive_new_*` stream methods generated by zbus.
    #[zbus(signal)]
    fn new_icon(&self) -> zbus::Result<()>;

    #[zbus(signal)]
    fn new_attention_icon(&self) -> zbus::Result<()>;

    #[zbus(signal)]
    fn new_overlay_icon(&self) -> zbus::Result<()>;

    #[zbus(signal)]
    fn new_title(&self) -> zbus::Result<()>;

    #[zbus(signal)]
    fn new_status(&self, status: &str) -> zbus::Result<()>;

    #[zbus(signal)]
    fn new_tool_tip(&self) -> zbus::Result<()>;
}

/// Parse the `service` string passed to `RegisterStatusNotifierItem` into a
/// (bus_name, object_path) pair.
///
/// Rules (per spec):
/// - Empty → use caller's unique bus name + `/StatusNotifierItem`
/// - Starts with `/` → object path on the caller's bus
/// - Contains `/` after a non-empty prefix → `busname/objectpath`
/// - Otherwise → bus name, use `/StatusNotifierItem` as default path
pub(crate) fn parse_service(sender_unique: &str, service: &str) -> (String, OwnedObjectPath) {
    let default_path =
        OwnedObjectPath::try_from("/StatusNotifierItem").expect("valid static path");

    if service.is_empty() {
        (sender_unique.to_string(), default_path)
    } else if service.starts_with('/') {
        (
            sender_unique.to_string(),
            OwnedObjectPath::try_from(service).unwrap_or(default_path),
        )
    } else if let Some(slash) = service.find('/') {
        let bus = &service[..slash];
        let path = &service[slash..];
        (
            bus.to_string(),
            OwnedObjectPath::try_from(path).unwrap_or(default_path),
        )
    } else {
        (service.to_string(), default_path)
    }
}

/// Build a canonical item key from bus name and object path.
pub(crate) fn item_key(bus_name: &str, obj_path: &OwnedObjectPath) -> String {
    format!("{bus_name}{obj_path}")
}

/// Read all properties from an SNI item and return a [`StatusNotifierItem`].
///
/// Returns `Err` only on hard D-Bus errors; missing optional properties are
/// silently treated as absent.
pub(crate) async fn load_item(
    conn: &Connection,
    bus_name: &str,
    obj_path: &OwnedObjectPath,
) -> Result<StatusNotifierItem> {
    let proxy = StatusNotifierItemInterfaceProxy::builder(conn)
        .destination(bus_name.to_string())?
        .path(obj_path.clone())?
        .build()
        .await?;

    let id = proxy.id().await.unwrap_or_default();
    let title = proxy.title().await.unwrap_or_default();
    let status_str = proxy.status().await.unwrap_or_default();
    let status = ItemStatus::from_str(&status_str).unwrap_or_default();

    // Primary icon
    let icon_name = proxy.icon_name().await.ok();
    let icon_pixmaps = proxy
        .icon_pixmap()
        .await
        .unwrap_or_default()
        .into_iter()
        .map(|(w, h, d)| decode_pixmap(w, h, d))
        .collect::<Vec<TrayIconPixmap>>();
    let icon = resolve_icon(icon_name.as_deref(), icon_pixmaps)
        .unwrap_or(crate::types::TrayIcon::Named(String::new()));

    // Overlay icon
    let overlay_name = proxy.overlay_icon_name().await.ok();
    let overlay_pixmaps = proxy
        .overlay_icon_pixmap()
        .await
        .unwrap_or_default()
        .into_iter()
        .map(|(w, h, d)| decode_pixmap(w, h, d))
        .collect::<Vec<TrayIconPixmap>>();
    let overlay_icon = resolve_icon(overlay_name.as_deref(), overlay_pixmaps);

    // Attention icon
    let attn_name = proxy.attention_icon_name().await.ok();
    let attn_pixmaps = proxy
        .attention_icon_pixmap()
        .await
        .unwrap_or_default()
        .into_iter()
        .map(|(w, h, d)| decode_pixmap(w, h, d))
        .collect::<Vec<TrayIconPixmap>>();
    let attention_icon = resolve_icon(attn_name.as_deref(), attn_pixmaps);

    // Menu path
    let menu_path = proxy.menu().await.ok().and_then(|p| {
        if p.as_str() == "/" || p.as_str().is_empty() {
            None
        } else {
            Some(p)
        }
    });

    // Tooltip: title field of the tooltip struct
    let tooltip = proxy
        .tool_tip()
        .await
        .ok()
        .map(|(_, _, title, desc)| {
            if !title.is_empty() {
                title
            } else {
                desc
            }
        })
        .filter(|s| !s.is_empty());

    Ok(StatusNotifierItem {
        id,
        title,
        icon,
        overlay_icon,
        attention_icon,
        menu_path,
        status,
        tooltip,
        bus_name: bus_name.to_string(),
        object_path: obj_path.clone(),
    })
}

/// Spawn a background task that watches for SNI signals from `bus_name/obj_path`
/// and sends `TrayEvent::ItemUpdated` on each change.
///
/// Returns a `JoinHandle`; dropping it cancels the watcher.
pub(crate) fn spawn_item_watcher(
    conn: Connection,
    bus_name: String,
    obj_path: OwnedObjectPath,
    key: String,
    tx: tokio::sync::mpsc::Sender<crate::types::TrayEvent>,
) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        if let Err(e) = watch_item(conn, bus_name, obj_path, key, tx).await {
            tracing::debug!("item watcher ended: {e}");
        }
    })
}

async fn watch_item(
    conn: Connection,
    bus_name: String,
    obj_path: OwnedObjectPath,
    key: String,
    tx: tokio::sync::mpsc::Sender<crate::types::TrayEvent>,
) -> Result<()> {
    use futures_util::StreamExt;

    let proxy = StatusNotifierItemInterfaceProxy::builder(&conn)
        .destination(bus_name)?
        .path(obj_path.clone())?
        .build()
        .await?;

    // Combine all signal streams into a single select loop.
    let mut new_icon = proxy.receive_new_icon().await?;
    let mut new_attn = proxy.receive_new_attention_icon().await?;
    let mut new_overlay = proxy.receive_new_overlay_icon().await?;
    let mut new_title = proxy.receive_new_title().await?;
    let mut new_status = proxy.receive_new_status().await?;
    let mut new_tip = proxy.receive_new_tool_tip().await?;

    loop {
        tokio::select! {
            msg = new_icon.next() => {
                if msg.is_none() { break; }
                let _ = tx.send(crate::types::TrayEvent::ItemUpdated {
                    id: key.clone(),
                    property: crate::types::UpdatedProperty::Icon,
                }).await;
            }
            msg = new_attn.next() => {
                if msg.is_none() { break; }
                let _ = tx.send(crate::types::TrayEvent::ItemUpdated {
                    id: key.clone(),
                    property: crate::types::UpdatedProperty::AttentionIcon,
                }).await;
            }
            msg = new_overlay.next() => {
                if msg.is_none() { break; }
                let _ = tx.send(crate::types::TrayEvent::ItemUpdated {
                    id: key.clone(),
                    property: crate::types::UpdatedProperty::OverlayIcon,
                }).await;
            }
            msg = new_title.next() => {
                if msg.is_none() { break; }
                let _ = tx.send(crate::types::TrayEvent::ItemUpdated {
                    id: key.clone(),
                    property: crate::types::UpdatedProperty::Title,
                }).await;
            }
            sig = new_status.next() => {
                match sig {
                    None => break,
                    Some(s) => {
                        if let Ok(args) = s.args() {
                            let status = ItemStatus::from_str(args.status).unwrap_or_default();
                            let _ = tx.send(crate::types::TrayEvent::ItemUpdated {
                                id: key.clone(),
                                property: crate::types::UpdatedProperty::Status(status),
                            }).await;
                        }
                    }
                }
            }
            msg = new_tip.next() => {
                if msg.is_none() { break; }
                let _ = tx.send(crate::types::TrayEvent::ItemUpdated {
                    id: key.clone(),
                    property: crate::types::UpdatedProperty::Tooltip,
                }).await;
            }
        }
    }

    Ok(())
}
