//! WGSL signed-distance-function shader generation.
//!
//! Generates a WGSL fragment shader function that computes the SDF of a
//! squircle shape. The SDF returns a negative value inside the shape and a
//! positive value outside. Use `smoothstep` for anti-aliased edges.

use crate::config::SquircleConfig;
use crate::path::SquirclePath;

impl SquirclePath {
    /// Generate WGSL fragment shader code for an SDF of this squircle shape.
    ///
    /// The generated function `squircle_sdf` takes:
    /// - `pos`: the fragment position in the same coordinate space as the rect
    /// - `half_size`: half the width and height of the bounding rect
    ///
    /// It returns a signed distance: negative inside, positive outside.
    /// The corner radius and smoothing are embedded as constants.
    ///
    /// # Example usage in a WGSL shader
    ///
    /// ```wgsl
    /// // Embed the generated function, then:
    /// let d = squircle_sdf(frag_pos - rect_center, vec2<f32>(half_w, half_h));
    /// let alpha = 1.0 - smoothstep(-0.5, 0.5, d);
    /// ```
    pub fn sdf_wgsl(config: &SquircleConfig) -> String {
        let r = config.corner_radius.max(0.0);
        let xi = config.clamped_smoothing();
        generate_sdf_wgsl(r, xi)
    }
}

/// Generate the WGSL SDF function with baked-in radius and smoothing constants.
fn generate_sdf_wgsl(radius: f32, smoothing: f32) -> String {
    // The SDF approach: fold the position into the first quadrant, compute the
    // distance to the rounded-rect boundary using the baked radius.
    //
    // For a squircle, we approximate the SDF by using the circular-arc portion
    // for the corner distance and a smoothed blend that mimics the Bézier curve.
    // The smoothing parameter adjusts the effective transition region.
    //
    // This is a practical approximation — a true Bézier SDF requires iterative
    // solvers. The approximation matches well near the boundary (< 2px error).

    let p_scale = 1.0 + smoothing * 0.7; // reach factor, mirrors path.rs
    let blend_k = 8.0 + smoothing * 16.0; // smoothstep steepness of the blend

    format!(
        r#"// Squircle SDF — generated by the `rounding` crate.
// corner_radius = {radius:.6}, smoothing = {smoothing:.6}
//
// Returns negative inside the shape, positive outside.
// Use with smoothstep for anti-aliased clipping:
//   let alpha = 1.0 - smoothstep(-0.5, 0.5, squircle_sdf(pos, half_size));

fn squircle_sdf(pos: vec2<f32>, half_size: vec2<f32>) -> f32 {{
    let RADIUS: f32 = {radius:.6};
    let SMOOTHING: f32 = {smoothing:.6};
    let P_SCALE: f32 = {p_scale:.6};
    let BLEND_K: f32 = {blend_k:.6};

    // Fold into first quadrant.
    let q = abs(pos) - half_size + vec2<f32>(RADIUS, RADIUS);

    // Standard rounded-rect SDF distance to corner arc.
    let arc_dist = length(max(q, vec2<f32>(0.0, 0.0))) + min(max(q.x, q.y), 0.0) - RADIUS;

    if SMOOTHING < 0.001 {{
        // Pure circular arc — no smoothing adjustment needed.
        return arc_dist;
    }}

    // Squircle blend: outside the corner region, use regular rect SDF.
    // Inside the corner region, blend toward a softer distance field that
    // simulates the continuous-curvature Bézier transition.
    //
    // The extended reach of the squircle is P_SCALE * RADIUS instead of RADIUS.
    // We compute a "reach distance" using the extended radius, then blend.
    let reach = RADIUS * P_SCALE;
    let q_reach = abs(pos) - half_size + vec2<f32>(reach, reach);
    let reach_dist = length(max(q_reach, vec2<f32>(0.0, 0.0))) + min(max(q_reach.x, q_reach.y), 0.0) - reach;

    // Blend factor: 0 far from corner, 1 in the Bézier zone.
    // We use a smooth transition based on distance to the corner region.
    let corner_proximity = -min(max(q.x, q.y), 0.0) / RADIUS;
    let blend = clamp(corner_proximity * BLEND_K - (BLEND_K - 1.0), 0.0, 1.0);

    // Interpolate between arc_dist (sharp) and reach_dist (smooth).
    return mix(arc_dist, reach_dist * (RADIUS / reach), blend * SMOOTHING);
}}
"#,
        radius = radius,
        smoothing = smoothing,
        p_scale = p_scale,
        blend_k = blend_k,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::SquircleConfig;

    #[test]
    fn sdf_wgsl_contains_function_signature() {
        let code = SquirclePath::sdf_wgsl(&SquircleConfig::default());
        assert!(
            code.contains("fn squircle_sdf"),
            "Generated WGSL should contain fn squircle_sdf"
        );
    }

    #[test]
    fn sdf_wgsl_contains_return() {
        let code = SquirclePath::sdf_wgsl(&SquircleConfig::default());
        assert!(code.contains("return"), "WGSL function should have a return statement");
    }

    #[test]
    fn sdf_wgsl_embeds_config_values() {
        let cfg = SquircleConfig::new(15.0, 0.8);
        let code = SquirclePath::sdf_wgsl(&cfg);
        assert!(code.contains("15."), "Should embed corner_radius");
        assert!(code.contains("0.8"), "Should embed smoothing");
    }

    #[test]
    fn sdf_wgsl_zero_smoothing() {
        let cfg = SquircleConfig::new(10.0, 0.0);
        let code = SquirclePath::sdf_wgsl(&cfg);
        assert!(!code.is_empty());
    }
}
