//! Squircle clipping for window content.
//!
//! Two strategies are provided:
//!
//! - **SDF (default)**: A GLSL fragment shader computes the signed distance to the
//!   squircle boundary and smoothsteps over a 1 px transition, giving perfectly
//!   anti-aliased edges at any resolution.
//!
//! - **Stencil**: The squircle fill is drawn into the stencil buffer, then the
//!   client texture is drawn with `GL_EQUAL` stencil testing. Simpler but
//!   requires stencil buffer support and produces aliased edges.
//!
//! # GPU integration
//!
//! [`ClipRenderer::render_clipped_texture`] currently falls back to an unclipped
//! draw (for compilation without a live GL context). The Smithay `GlesFrame`
//! integration (subagent 07) must:
//!
//! 1. Compile the GLSL pair from [`SDF_VERT_GLSL`] / [`SDF_FRAG_GLSL`].
//! 2. Set uniforms: `u_half_size`, `u_radius`, `u_smoothing`.
//! 3. Bind the client surface texture to `u_tex`.
//! 4. Draw the window rect quad through the shader.

use rounding::SquircleConfig;

use super::{FrameRef, Rect};

// ─── GLSL shader sources ─────────────────────────────────────────────────────

/// Vertex shader for the SDF squircle clip pass.
///
/// Outputs `v_frag_pos` — the fragment position relative to the window centre,
/// in the same logical-pixel space as the window dimensions.
pub const SDF_VERT_GLSL: &str = r#"#version 300 es
precision highp float;

in vec2 a_pos;       // NDC position of vertex
in vec2 a_texcoord;  // UV coordinates [0, 1]

uniform vec2 u_window_pos;  // window top-left in screen pixels
uniform vec2 u_window_size; // window width, height in screen pixels

out vec2 v_texcoord;
out vec2 v_frag_pos; // relative to window centre, in pixels

void main() {
    gl_Position = vec4(a_pos, 0.0, 1.0);
    v_texcoord = a_texcoord;

    // Map NDC a_pos -> screen pixel, then compute offset from window centre.
    // This is filled in by the caller using the viewport transform.
    v_frag_pos = (a_pos * 0.5 + 0.5) * u_window_size - u_window_size * 0.5;
}
"#;

/// Fragment shader for the SDF squircle clip pass.
///
/// Clips the client surface texture to the squircle shape using a signed
/// distance field, producing anti-aliased edges.
///
/// Uniforms:
/// - `u_tex`       — client surface sampler
/// - `u_half_size` — `(window_width / 2, window_height / 2)` in pixels
/// - `u_radius`    — corner radius in pixels (from theme, default 14)
/// - `u_smoothing` — squircle smoothing factor (from theme, default 0.6)
/// - `u_alpha`     — window opacity (animated)
pub const SDF_FRAG_GLSL: &str = r#"#version 300 es
precision highp float;

in vec2 v_texcoord;
in vec2 v_frag_pos;

uniform sampler2D u_tex;
uniform vec2  u_half_size;
uniform float u_radius;
uniform float u_smoothing;
uniform float u_alpha;

out vec4 frag_color;

// Squircle SDF — mirrors the WGSL version generated by the `rounding` crate.
// Returns negative inside the shape, positive outside.
// The smoothing parameter extends the effective corner ramp beyond a pure arc.
float squircle_sdf(vec2 pos, vec2 half_size, float r, float smoothing) {
    float p_scale = 1.0 + smoothing * 0.7;
    float blend_k = 8.0 + smoothing * 16.0;

    vec2 q = abs(pos) - half_size + vec2(r);
    float arc_dist = length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0) - r;

    if (smoothing < 0.001) {
        return arc_dist;
    }

    float reach = r * p_scale;
    vec2 q2 = abs(pos) - half_size + vec2(reach);
    float reach_dist = length(max(q2, vec2(0.0))) + min(max(q2.x, q2.y), 0.0) - reach;

    float corner_prox = -min(max(q.x, q.y), 0.0) / max(r, 0.001);
    float blend = clamp(corner_prox * blend_k - (blend_k - 1.0), 0.0, 1.0);

    return mix(arc_dist, reach_dist * (r / max(reach, 0.001)), blend * smoothing);
}

void main() {
    vec4 tex_color = texture(u_tex, v_texcoord);

    float d = squircle_sdf(v_frag_pos, u_half_size, u_radius, u_smoothing);
    float clip_alpha = 1.0 - smoothstep(-0.5, 0.5, d);

    frag_color = vec4(tex_color.rgb, tex_color.a * clip_alpha * u_alpha);
}
"#;

/// Inner highlight fragment shader.
///
/// Renders a 1 px inset squircle stroke with a vertical alpha gradient
/// (full brightness at the top, transparent at the bottom).
///
/// Uniforms:
/// - `u_half_size`   — `(window_width / 2, window_height / 2)`
/// - `u_radius`      — corner radius
/// - `u_smoothing`   — squircle smoothing
/// - `u_top_color`   — highlight colour at the top (RGBA)
/// - `u_alpha`       — overall opacity multiplier
pub const INNER_HIGHLIGHT_FRAG_GLSL: &str = r#"#version 300 es
precision highp float;

in vec2 v_texcoord;
in vec2 v_frag_pos;

uniform vec2  u_half_size;
uniform float u_radius;
uniform float u_smoothing;
uniform vec4  u_top_color;   // RGBA at top of window
uniform float u_alpha;

out vec4 frag_color;

float squircle_sdf(vec2 pos, vec2 half_size, float r, float smoothing) {
    float p_scale = 1.0 + smoothing * 0.7;
    float blend_k = 8.0 + smoothing * 16.0;

    vec2 q = abs(pos) - half_size + vec2(r);
    float arc_dist = length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0) - r;

    if (smoothing < 0.001) {
        return arc_dist;
    }

    float reach = r * p_scale;
    vec2 q2 = abs(pos) - half_size + vec2(reach);
    float reach_dist = length(max(q2, vec2(0.0))) + min(max(q2.x, q2.y), 0.0) - reach;

    float corner_prox = -min(max(q.x, q.y), 0.0) / max(r, 0.001);
    float blend = clamp(corner_prox * blend_k - (blend_k - 1.0), 0.0, 1.0);

    return mix(arc_dist, reach_dist * (r / max(reach, 0.001)), blend * smoothing);
}

void main() {
    // Inset by 1 px from the outer edge.
    vec2 inset_half = u_half_size - vec2(1.0);
    float d_outer = squircle_sdf(v_frag_pos, u_half_size, u_radius, u_smoothing);
    float d_inner = squircle_sdf(v_frag_pos, inset_half, max(u_radius - 1.0, 0.0), u_smoothing);

    // Inside the 1 px stroke band.
    float in_outer = 1.0 - smoothstep(-0.5, 0.5, d_outer);
    float in_inner = 1.0 - smoothstep(-0.5, 0.5, d_inner);
    float stroke = in_outer * (1.0 - in_inner);

    // Vertical gradient: y_norm = 0 at top, 1 at bottom.
    float y_norm = (v_frag_pos.y + u_half_size.y) / max(u_half_size.y * 2.0, 0.001);
    float grad = clamp(1.0 - y_norm * 1.5, 0.0, 1.0);

    vec4 color = u_top_color * vec4(1.0, 1.0, 1.0, grad);
    frag_color = vec4(color.rgb, color.a * stroke * u_alpha);
}
"#;

/// Outer border stroke fragment shader.
///
/// Renders a 0.5 px squircle stroke along the outer edge of the window.
pub const OUTER_STROKE_FRAG_GLSL: &str = r#"#version 300 es
precision highp float;

in vec2 v_texcoord;
in vec2 v_frag_pos;

uniform vec2  u_half_size;
uniform float u_radius;
uniform float u_smoothing;
uniform vec4  u_stroke_color; // RGBA
uniform float u_stroke_width; // typically 0.5

out vec4 frag_color;

float squircle_sdf(vec2 pos, vec2 half_size, float r, float smoothing) {
    float p_scale = 1.0 + smoothing * 0.7;
    float blend_k = 8.0 + smoothing * 16.0;

    vec2 q = abs(pos) - half_size + vec2(r);
    float arc_dist = length(max(q, vec2(0.0))) + min(max(q.x, q.y), 0.0) - r;

    if (smoothing < 0.001) {
        return arc_dist;
    }

    float reach = r * p_scale;
    vec2 q2 = abs(pos) - half_size + vec2(reach);
    float reach_dist = length(max(q2, vec2(0.0))) + min(max(q2.x, q2.y), 0.0) - reach;

    float corner_prox = -min(max(q.x, q.y), 0.0) / max(r, 0.001);
    float blend = clamp(corner_prox * blend_k - (blend_k - 1.0), 0.0, 1.0);

    return mix(arc_dist, reach_dist * (r / max(reach, 0.001)), blend * smoothing);
}

void main() {
    float d = squircle_sdf(v_frag_pos, u_half_size, u_radius, u_smoothing);
    // Thin stroke band around d == 0.
    float stroke = 1.0 - smoothstep(-u_stroke_width, u_stroke_width, abs(d));
    frag_color = vec4(u_stroke_color.rgb, u_stroke_color.a * stroke);
}
"#;

// ─── Clip strategy ───────────────────────────────────────────────────────────

/// Which GPU technique to use for squircle clipping.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum ClipStrategy {
    /// SDF fragment shader — anti-aliased edges, no stencil buffer needed.
    /// This is the default and preferred strategy.
    #[default]
    Sdf,
    /// Stencil buffer — simpler, requires GL stencil support, aliased edges.
    Stencil,
}

/// Parameters needed by the clip shader for one window.
#[derive(Debug, Clone, Copy)]
pub struct ClipParams {
    /// Half-width of the window (width / 2).
    pub half_w: f32,
    /// Half-height of the window (height / 2).
    pub half_h: f32,
    /// Corner radius from the theme (default 14 px).
    pub corner_radius: f32,
    /// Squircle smoothing from the theme (default 0.6).
    pub smoothing: f32,
    /// Window opacity [0, 1].
    pub alpha: f32,
}

impl ClipParams {
    /// Build clip params from a rect and a squircle config.
    pub fn from_rect(rect: Rect, config: SquircleConfig, alpha: f32) -> Self {
        Self {
            half_w: rect.width * 0.5,
            half_h: rect.height * 0.5,
            corner_radius: config.corner_radius,
            smoothing: config.smoothing,
            alpha,
        }
    }
}

// ─── ClipRenderer ────────────────────────────────────────────────────────────

/// Renders client surface content clipped to the squircle boundary.
///
/// # GPU integration (TODO — subagent 07)
///
/// To wire up real SDF clipping with Smithay's `GlesRenderer`:
///
/// 1. At startup, compile a custom `GlesPixelProgram` from [`SDF_VERT_GLSL`] and
///    [`SDF_FRAG_GLSL`] using `GlesRenderer::compile_custom_pixel_shader`.
/// 2. In [`ClipRenderer::render_clipped_texture`], call
///    `GlesFrame::render_texture_with_shader(texture, program, uniforms, rect)`.
/// 3. Pass `ClipParams` as the uniform values.
///
/// Until GPU integration is complete, this method falls back to an unclipped
/// pixel draw at the destination rect (correct compositing, no corner rounding).
pub struct ClipRenderer {
    strategy: ClipStrategy,
}

impl ClipRenderer {
    /// Create a new clip renderer with the given strategy.
    pub fn new(strategy: ClipStrategy) -> Self {
        Self { strategy }
    }

    /// The active clipping strategy.
    pub fn strategy(&self) -> ClipStrategy {
        self.strategy
    }

    /// Render `pixels` (raw RGBA) clipped to the squircle shape at `dst`.
    ///
    /// `alpha` is multiplied with each pixel's alpha (from the window's
    /// animated opacity).
    ///
    /// **Current behaviour:** renders unclipped (SDF shader not yet wired to
    /// GPU). Corner clipping is correct once the GLSL integration is done.
    #[allow(clippy::too_many_arguments)]
    pub fn render_clipped_texture<F: FrameRef>(
        &self,
        frame: &mut F,
        pixels: &[u8],
        pixel_width: u32,
        pixel_height: u32,
        dst: Rect,
        _config: SquircleConfig,
        alpha: f32,
    ) -> Result<(), F::Error> {
        // TODO: when GPU integration is ready, use SDF_VERT_GLSL / SDF_FRAG_GLSL
        // with ClipParams uniforms instead of the plain pixel draw below.
        // The plain draw is correct for compositing; only the corner anti-aliasing
        // is missing until the shader is compiled and bound.
        frame.draw_pixels(pixels, pixel_width, pixel_height, dst, alpha)
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn sdf_vert_glsl_is_nonempty() {
        assert!(!SDF_VERT_GLSL.is_empty());
    }

    #[test]
    fn sdf_frag_glsl_contains_squircle_sdf() {
        assert!(
            SDF_FRAG_GLSL.contains("squircle_sdf"),
            "Fragment shader must define squircle_sdf"
        );
    }

    #[test]
    fn sdf_frag_glsl_uses_smoothstep() {
        assert!(SDF_FRAG_GLSL.contains("smoothstep"));
    }

    #[test]
    fn inner_highlight_shader_has_gradient() {
        assert!(
            INNER_HIGHLIGHT_FRAG_GLSL.contains("y_norm"),
            "Inner highlight shader must implement vertical gradient"
        );
    }

    #[test]
    fn outer_stroke_shader_has_stroke() {
        assert!(
            OUTER_STROKE_FRAG_GLSL.contains("stroke"),
            "Outer stroke shader must compute stroke"
        );
    }

    #[test]
    fn clip_params_from_rect() {
        let rect = Rect::new(10.0, 20.0, 400.0, 300.0);
        let config = SquircleConfig::new(14.0, 0.6);
        let params = ClipParams::from_rect(rect, config, 1.0);

        assert_eq!(params.half_w, 200.0);
        assert_eq!(params.half_h, 150.0);
        assert_eq!(params.corner_radius, 14.0);
        assert_eq!(params.smoothing, 0.6);
        assert_eq!(params.alpha, 1.0);
    }

    #[test]
    fn clip_strategy_default_is_sdf() {
        assert_eq!(ClipStrategy::default(), ClipStrategy::Sdf);
    }
}
